import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { cn } from "@/lib/utils";
import { AllProviders } from "@/components/providers/allProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {

  const messages = await getMessages()   

  return (
    <html lang={locale} className="h-screen">
      <body className={cn(inter.className, "h-full")}>
      <NextIntlClientProvider messages={messages}>
      <AllProviders params={{ locale }}>
        {children}
      </AllProviders>
      </NextIntlClientProvider>
      </body>
    </html>
  );
}
